/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package faturatakip;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emre USTA
 */
public class FaturaTakip extends javax.swing.JFrame {

    /**
     * Creates new form FaturaTakip
     */
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultListModel dlm = new DefaultListModel();
    DefaultListModel dlmList = new DefaultListModel();
    DefaultListModel dlmAbone = new DefaultListModel();
    DefaultTableModel dtm2 = new DefaultTableModel();

    public FaturaTakip() {
        initComponents();
        setTitle("Fatura Bilgilendirme");
        listFatura.setModel(dlm);
        listFaturaOdeme.setModel(dlmList);
        listAboneDurum.setModel(dlmAbone);
        tblDosyaOku.setModel(dtm2);

        dtm.setColumnIdentifiers(new String[]{"FATURANO", "FATURATURU", "ILKODEMETARIHI", "SONODEMETARIHI", "FATURATUTARI", "ADRES", "ABONE"});
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select f from Fatura f ");
        List<Fatura> faturalar = q.getResultList();
        dtm.setRowCount(0);
        for (Fatura f : faturalar) {
            dtm.addRow(new Object[]{f.getFaturano(), f.getFaturaturu(), f.getIlkodemetarihi(), f.getSonodemetarihi(), f.getFaturatutari(), f.getAdres(), f.getAbone()});
        }
        tblGoster.setModel(dtm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFaturaTakip = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGoster = new javax.swing.JTable();
        btnEkle = new javax.swing.JButton();
        btnSİl = new javax.swing.JButton();
        btnDegistir = new javax.swing.JButton();
        btnPersonelDegistir = new javax.swing.JButton();
        btnFaturalar = new javax.swing.JButton();
        btnAdresler = new javax.swing.JButton();
        btnFaturaÖdemeleri = new javax.swing.JButton();
        btnAboneDurum = new javax.swing.JButton();
        btnSorgu = new javax.swing.JButton();
        btnFaturaDosyaYazdir = new javax.swing.JButton();
        btnAboneDosyaYazdir = new javax.swing.JButton();
        btnDosyaOku = new javax.swing.JButton();
        btnYenile = new javax.swing.JButton();
        PanelSil = new javax.swing.JPanel();
        lblBilgi = new javax.swing.JLabel();
        lblFaturaNo = new javax.swing.JLabel();
        txtFaturaNo = new javax.swing.JTextField();
        btnSil = new javax.swing.JButton();
        btnGeri = new javax.swing.JButton();
        PanelDegistir = new javax.swing.JPanel();
        lblDegistirmek = new javax.swing.JLabel();
        lblfaturaNoDegistir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFaturaNoDegistir = new javax.swing.JTextField();
        txtYeniFatura = new javax.swing.JTextField();
        btnDegistirD = new javax.swing.JButton();
        btnGeriDegistir = new javax.swing.JButton();
        PanelFaturaListele = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listFatura = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnListele = new javax.swing.JButton();
        btnGeriFatura = new javax.swing.JButton();
        PanelFaturaAdresleri = new javax.swing.JPanel();
        lblFaturaAdresBilgi = new javax.swing.JLabel();
        cmbAdresler = new javax.swing.JComboBox<>();
        btnListeleAdres = new javax.swing.JButton();
        btnGeriAdres = new javax.swing.JButton();
        PanelFaturaOdemeleri = new javax.swing.JPanel();
        lblFaturaOdemeBilgi = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listFaturaOdeme = new javax.swing.JList<>();
        btnListeleOdeme = new javax.swing.JButton();
        btnGeriOdeme = new javax.swing.JButton();
        btnToplamOdeme = new javax.swing.JButton();
        txtToplamOdeme = new javax.swing.JTextField();
        PanelAboneDurum = new javax.swing.JPanel();
        lblAboneDurumGoster = new javax.swing.JLabel();
        lblToplamAboneSayisi = new javax.swing.JLabel();
        txtToplamAbone = new javax.swing.JTextField();
        btnGoster = new javax.swing.JButton();
        btnGeriAboneDurum = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtOrtalamaOdeme = new javax.swing.JTextField();
        btnHesapla = new javax.swing.JButton();
        lblSonOdeme = new javax.swing.JLabel();
        btnTarihGoster = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listAboneDurum = new javax.swing.JList<>();
        PanelSorgu = new javax.swing.JPanel();
        lblBilgiSorgulama = new javax.swing.JLabel();
        lblFaturaNoSorgu = new javax.swing.JLabel();
        txtFaturaNoSorgu = new javax.swing.JTextField();
        btnSorgula = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtaSorguSonuc = new javax.swing.JTextArea();
        btnGeriSorguSonuc = new javax.swing.JButton();
        PanelDosyaOku = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDosyaOku = new javax.swing.JTable();
        btnFaturaOku = new javax.swing.JButton();
        btnPersonelOku = new javax.swing.JButton();
        btnGeriOkuma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        tblGoster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblGoster);

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        btnSİl.setText("Sil");
        btnSİl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSİlActionPerformed(evt);
            }
        });

        btnDegistir.setText("Değiştir");
        btnDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDegistirActionPerformed(evt);
            }
        });

        btnPersonelDegistir.setText("Personel Degistir");
        btnPersonelDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonelDegistirActionPerformed(evt);
            }
        });

        btnFaturalar.setText("Faturalar");
        btnFaturalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaturalarActionPerformed(evt);
            }
        });

        btnAdresler.setText("Fatura Adresleri");
        btnAdresler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdreslerActionPerformed(evt);
            }
        });

        btnFaturaÖdemeleri.setText("Fatura Ödemeleri");
        btnFaturaÖdemeleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaturaÖdemeleriActionPerformed(evt);
            }
        });

        btnAboneDurum.setText("Abone Durum");
        btnAboneDurum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboneDurumActionPerformed(evt);
            }
        });

        btnSorgu.setText("Sorgu");
        btnSorgu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorguActionPerformed(evt);
            }
        });

        btnFaturaDosyaYazdir.setText("Faturayı Dosyaya Yazdır");
        btnFaturaDosyaYazdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaturaDosyaYazdirActionPerformed(evt);
            }
        });

        btnAboneDosyaYazdir.setText("Aboneyi Dosyaya Yazdır");
        btnAboneDosyaYazdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboneDosyaYazdirActionPerformed(evt);
            }
        });

        btnDosyaOku.setText("Fatura Dosya Oku");
        btnDosyaOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosyaOkuActionPerformed(evt);
            }
        });

        btnYenile.setText("Yenile");
        btnYenile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYenileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFaturaTakipLayout = new javax.swing.GroupLayout(PanelFaturaTakip);
        PanelFaturaTakip.setLayout(PanelFaturaTakipLayout);
        PanelFaturaTakipLayout.setHorizontalGroup(
            PanelFaturaTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFaturaTakipLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(PanelFaturaTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFaturaDosyaYazdir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSorgu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDegistir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSİl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAboneDosyaYazdir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDosyaOku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnYenile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PanelFaturaTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFaturaTakipLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(PanelFaturaTakipLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(btnFaturalar)
                        .addGap(48, 48, 48)
                        .addComponent(btnAdresler)
                        .addGap(49, 49, 49)
                        .addComponent(btnAboneDurum)
                        .addGap(59, 59, 59)
                        .addComponent(btnFaturaÖdemeleri)
                        .addGap(62, 62, 62)
                        .addComponent(btnPersonelDegistir)
                        .addGap(53, 53, 53))))
        );
        PanelFaturaTakipLayout.setVerticalGroup(
            PanelFaturaTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFaturaTakipLayout.createSequentialGroup()
                .addGroup(PanelFaturaTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFaturaTakipLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelFaturaTakipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAboneDurum)
                            .addComponent(btnFaturaÖdemeleri)
                            .addComponent(btnPersonelDegistir)
                            .addComponent(btnAdresler)
                            .addComponent(btnFaturalar)))
                    .addGroup(PanelFaturaTakipLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnEkle)
                        .addGap(18, 18, 18)
                        .addComponent(btnSİl)
                        .addGap(18, 18, 18)
                        .addComponent(btnDegistir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSorgu)
                        .addGap(18, 18, 18)
                        .addComponent(btnFaturaDosyaYazdir)
                        .addGap(18, 18, 18)
                        .addComponent(btnAboneDosyaYazdir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDosyaOku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnYenile)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        getContentPane().add(PanelFaturaTakip, "card2");

        lblBilgi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBilgi.setText("Fatura Numarası Giriniz");

        lblFaturaNo.setText("Fatura  Numarası :");

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        btnGeri.setText("Geri");
        btnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSilLayout = new javax.swing.GroupLayout(PanelSil);
        PanelSil.setLayout(PanelSilLayout);
        PanelSilLayout.setHorizontalGroup(
            PanelSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSilLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(PanelSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBilgi)
                    .addGroup(PanelSilLayout.createSequentialGroup()
                        .addComponent(lblFaturaNo)
                        .addGap(45, 45, 45)
                        .addGroup(PanelSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelSilLayout.createSequentialGroup()
                                .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGeri))
                            .addComponent(txtFaturaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(797, Short.MAX_VALUE))
        );
        PanelSilLayout.setVerticalGroup(
            PanelSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSilLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblBilgi)
                .addGap(34, 34, 34)
                .addGroup(PanelSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaturaNo)
                    .addComponent(txtFaturaNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(PanelSilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSil)
                    .addComponent(btnGeri))
                .addContainerGap(333, Short.MAX_VALUE))
        );

        getContentPane().add(PanelSil, "card3");

        lblDegistirmek.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblDegistirmek.setText("Değiştirmek İstediğiniz Verileri Giriniz");

        lblfaturaNoDegistir.setText("Fatura Numarası :");

        jLabel1.setText("Yeni Fatura Türü :");

        btnDegistirD.setText("Değiştir");
        btnDegistirD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDegistirDActionPerformed(evt);
            }
        });

        btnGeriDegistir.setText("Geri");
        btnGeriDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriDegistirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDegistirLayout = new javax.swing.GroupLayout(PanelDegistir);
        PanelDegistir.setLayout(PanelDegistirLayout);
        PanelDegistirLayout.setHorizontalGroup(
            PanelDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDegistirLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(PanelDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDegistirmek)
                    .addGroup(PanelDegistirLayout.createSequentialGroup()
                        .addGroup(PanelDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfaturaNoDegistir)
                            .addComponent(jLabel1))
                        .addGap(35, 35, 35)
                        .addGroup(PanelDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFaturaNoDegistir)
                            .addComponent(txtYeniFatura, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                .addContainerGap(691, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDegistirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDegistirD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGeriDegistir)
                .addGap(173, 173, 173))
        );
        PanelDegistirLayout.setVerticalGroup(
            PanelDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDegistirLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblDegistirmek)
                .addGap(62, 62, 62)
                .addGroup(PanelDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfaturaNoDegistir)
                    .addComponent(txtFaturaNoDegistir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtYeniFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDegistirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDegistirD)
                    .addComponent(btnGeriDegistir))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        getContentPane().add(PanelDegistir, "card4");

        jScrollPane2.setViewportView(listFatura);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Faturaları Listele");

        btnListele.setText("Listele");
        btnListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeleActionPerformed(evt);
            }
        });

        btnGeriFatura.setText("Geri");
        btnGeriFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriFaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFaturaListeleLayout = new javax.swing.GroupLayout(PanelFaturaListele);
        PanelFaturaListele.setLayout(PanelFaturaListeleLayout);
        PanelFaturaListeleLayout.setHorizontalGroup(
            PanelFaturaListeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFaturaListeleLayout.createSequentialGroup()
                .addGroup(PanelFaturaListeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelFaturaListeleLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListele)
                        .addGap(18, 18, 18)
                        .addComponent(btnGeriFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelFaturaListeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelFaturaListeleLayout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addComponent(jLabel2))
                        .addGroup(PanelFaturaListeleLayout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(559, Short.MAX_VALUE))
        );
        PanelFaturaListeleLayout.setVerticalGroup(
            PanelFaturaListeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFaturaListeleLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(PanelFaturaListeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGeriFatura)
                    .addComponent(btnListele))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        getContentPane().add(PanelFaturaListele, "card5");

        lblFaturaAdresBilgi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblFaturaAdresBilgi.setText("Fatura Adreslerini Listele");

        btnListeleAdres.setText("Listele");
        btnListeleAdres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeleAdresActionPerformed(evt);
            }
        });

        btnGeriAdres.setText("Geri");
        btnGeriAdres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriAdresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFaturaAdresleriLayout = new javax.swing.GroupLayout(PanelFaturaAdresleri);
        PanelFaturaAdresleri.setLayout(PanelFaturaAdresleriLayout);
        PanelFaturaAdresleriLayout.setHorizontalGroup(
            PanelFaturaAdresleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFaturaAdresleriLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(PanelFaturaAdresleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelFaturaAdresleriLayout.createSequentialGroup()
                        .addComponent(btnListeleAdres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGeriAdres))
                    .addGroup(PanelFaturaAdresleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblFaturaAdresBilgi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbAdresler, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(764, Short.MAX_VALUE))
        );
        PanelFaturaAdresleriLayout.setVerticalGroup(
            PanelFaturaAdresleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFaturaAdresleriLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblFaturaAdresBilgi)
                .addGap(48, 48, 48)
                .addComponent(cmbAdresler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(PanelFaturaAdresleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListeleAdres)
                    .addComponent(btnGeriAdres))
                .addContainerGap(301, Short.MAX_VALUE))
        );

        getContentPane().add(PanelFaturaAdresleri, "card6");

        lblFaturaOdemeBilgi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblFaturaOdemeBilgi.setText("Fatura Ödemeleri Listesi");

        jScrollPane3.setViewportView(listFaturaOdeme);

        btnListeleOdeme.setText("Listele");
        btnListeleOdeme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeleOdemeActionPerformed(evt);
            }
        });

        btnGeriOdeme.setText("Geri");
        btnGeriOdeme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriOdemeActionPerformed(evt);
            }
        });

        btnToplamOdeme.setText("Toplam Ödeme");
        btnToplamOdeme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToplamOdemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFaturaOdemeleriLayout = new javax.swing.GroupLayout(PanelFaturaOdemeleri);
        PanelFaturaOdemeleri.setLayout(PanelFaturaOdemeleriLayout);
        PanelFaturaOdemeleriLayout.setHorizontalGroup(
            PanelFaturaOdemeleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFaturaOdemeleriLayout.createSequentialGroup()
                .addGroup(PanelFaturaOdemeleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFaturaOdemeleriLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(PanelFaturaOdemeleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelFaturaOdemeleriLayout.createSequentialGroup()
                                .addComponent(btnListeleOdeme)
                                .addGap(18, 18, 18)
                                .addComponent(btnGeriOdeme, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(PanelFaturaOdemeleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelFaturaOdemeleriLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(txtToplamOdeme, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFaturaOdemeleriLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnToplamOdeme)
                                .addGap(9, 9, 9))))
                    .addGroup(PanelFaturaOdemeleriLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lblFaturaOdemeBilgi)))
                .addGap(195, 195, Short.MAX_VALUE))
        );
        PanelFaturaOdemeleriLayout.setVerticalGroup(
            PanelFaturaOdemeleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFaturaOdemeleriLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblFaturaOdemeBilgi)
                .addGap(38, 38, 38)
                .addGroup(PanelFaturaOdemeleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelFaturaOdemeleriLayout.createSequentialGroup()
                        .addComponent(txtToplamOdeme, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnToplamOdeme)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFaturaOdemeleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGeriOdeme)
                    .addComponent(btnListeleOdeme))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        getContentPane().add(PanelFaturaOdemeleri, "card7");

        lblAboneDurumGoster.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAboneDurumGoster.setText("Abone Durum Goster");

        lblToplamAboneSayisi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblToplamAboneSayisi.setText("Toplam Abone Sayısı : ");

        btnGoster.setText("Goster");
        btnGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGosterActionPerformed(evt);
            }
        });

        btnGeriAboneDurum.setText("Geri");
        btnGeriAboneDurum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriAboneDurumActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Ortalama Fatura Ödeme Tutarı :");

        btnHesapla.setText("Hesapla");
        btnHesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHesaplaActionPerformed(evt);
            }
        });

        lblSonOdeme.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSonOdeme.setText("Son Ödeme Tarihi :");

        btnTarihGoster.setText("Tarih Goster");
        btnTarihGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarihGosterActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(listAboneDurum);

        javax.swing.GroupLayout PanelAboneDurumLayout = new javax.swing.GroupLayout(PanelAboneDurum);
        PanelAboneDurum.setLayout(PanelAboneDurumLayout);
        PanelAboneDurumLayout.setHorizontalGroup(
            PanelAboneDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAboneDurumLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(lblAboneDurumGoster)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelAboneDurumLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(PanelAboneDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblToplamAboneSayisi)
                    .addComponent(jLabel3)
                    .addComponent(lblSonOdeme))
                .addGap(8, 8, 8)
                .addGroup(PanelAboneDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOrtalamaOdeme)
                    .addComponent(txtToplamAbone)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelAboneDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTarihGoster, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(btnHesapla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGeriAboneDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81))
        );
        PanelAboneDurumLayout.setVerticalGroup(
            PanelAboneDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAboneDurumLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblAboneDurumGoster)
                .addGap(40, 40, 40)
                .addGroup(PanelAboneDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblToplamAboneSayisi)
                    .addComponent(txtToplamAbone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoster))
                .addGap(18, 18, 18)
                .addGroup(PanelAboneDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOrtalamaOdeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHesapla))
                .addGroup(PanelAboneDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAboneDurumLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelAboneDurumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelAboneDurumLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnTarihGoster)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(btnGeriAboneDurum)
                        .addGap(40, 40, 40))
                    .addGroup(PanelAboneDurumLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblSonOdeme)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(PanelAboneDurum, "card8");

        lblBilgiSorgulama.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBilgiSorgulama.setText("Bilgi Sorgulama");

        lblFaturaNoSorgu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblFaturaNoSorgu.setText("Fatura No :");

        btnSorgula.setText("Sorgula");
        btnSorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorgulaActionPerformed(evt);
            }
        });

        txtaSorguSonuc.setColumns(20);
        txtaSorguSonuc.setRows(5);
        jScrollPane5.setViewportView(txtaSorguSonuc);

        btnGeriSorguSonuc.setText("Geri");
        btnGeriSorguSonuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriSorguSonucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSorguLayout = new javax.swing.GroupLayout(PanelSorgu);
        PanelSorgu.setLayout(PanelSorguLayout);
        PanelSorguLayout.setHorizontalGroup(
            PanelSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSorguLayout.createSequentialGroup()
                .addGroup(PanelSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelSorguLayout.createSequentialGroup()
                        .addContainerGap(164, Short.MAX_VALUE)
                        .addComponent(btnSorgula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGeriSorguSonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelSorguLayout.createSequentialGroup()
                            .addGap(162, 162, 162)
                            .addComponent(lblBilgiSorgulama))
                        .addGroup(PanelSorguLayout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(lblFaturaNoSorgu)
                            .addGap(31, 31, 31)
                            .addComponent(txtFaturaNoSorgu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        PanelSorguLayout.setVerticalGroup(
            PanelSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSorguLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblBilgiSorgulama)
                .addGap(38, 38, 38)
                .addGroup(PanelSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSorguLayout.createSequentialGroup()
                        .addGroup(PanelSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFaturaNoSorgu)
                            .addComponent(txtFaturaNoSorgu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelSorguLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSorgula)
                            .addComponent(btnGeriSorguSonuc)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        getContentPane().add(PanelSorgu, "card9");

        tblDosyaOku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tblDosyaOku);

        btnFaturaOku.setText("Fatura Oku");
        btnFaturaOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaturaOkuActionPerformed(evt);
            }
        });

        btnPersonelOku.setText("Personel Oku");
        btnPersonelOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonelOkuActionPerformed(evt);
            }
        });

        btnGeriOkuma.setText("Geri");
        btnGeriOkuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriOkumaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDosyaOkuLayout = new javax.swing.GroupLayout(PanelDosyaOku);
        PanelDosyaOku.setLayout(PanelDosyaOkuLayout);
        PanelDosyaOkuLayout.setHorizontalGroup(
            PanelDosyaOkuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDosyaOkuLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(PanelDosyaOkuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFaturaOku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPersonelOku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGeriOkuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        PanelDosyaOkuLayout.setVerticalGroup(
            PanelDosyaOkuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDosyaOkuLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(btnFaturaOku)
                .addGap(68, 68, 68)
                .addComponent(btnPersonelOku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGeriOkuma)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDosyaOkuLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        getContentPane().add(PanelDosyaOku, "card10");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        // TODO add your handling code here:

        FaturaEkleme fe = new FaturaEkleme();
        fe.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnSİlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSİlActionPerformed
        // TODO add your handling code here:
        PanelFaturaTakip.setVisible(false);
        PanelSil.setVisible(true);


    }//GEN-LAST:event_btnSİlActionPerformed

    private void btnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriActionPerformed
        // TODO add your handling code here:
        PanelSil.setVisible(false);
        PanelFaturaTakip.setVisible(true);
    }//GEN-LAST:event_btnGeriActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("delete from Fatura f WHERE f.faturano = :faturano");
        Query q1= em.createQuery("select f1 from Fatura f1");
        q.setParameter("faturano", Integer.valueOf(txtFaturaNo.getText()));
        
        List<Fatura> faturalar = q1.getResultList();
        
        for (Fatura f : faturalar) {
            if(!txtFaturaNo.getText().equals(String.valueOf(f.getFaturano()))){
                JOptionPane.showMessageDialog(this, "Girilen Fatura Numarası Sistemde Yer Almamaktadır.");
            }
        }
        em.getTransaction().begin();
        q.executeUpdate();
        em.getTransaction().commit();
        em.close();
        emf.close();


    }//GEN-LAST:event_btnSilActionPerformed

    private void btnDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDegistirActionPerformed
        // TODO add your handling code here:
        PanelFaturaTakip.setVisible(false);
        PanelDegistir.setVisible(true);

    }//GEN-LAST:event_btnDegistirActionPerformed

    private void btnGeriDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriDegistirActionPerformed
        // TODO add your handling code here:
        PanelFaturaTakip.setVisible(true);
        PanelDegistir.setVisible(false);
    }//GEN-LAST:event_btnGeriDegistirActionPerformed

    private void btnDegistirDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDegistirDActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("update Fatura f set f.faturaturu=:FATURATURU where f.faturano=:FATURANO");
        q.setParameter("FATURATURU", txtYeniFatura.getText());
        q.setParameter("FATURANO", Integer.parseInt(txtFaturaNoDegistir.getText()));
        em.getTransaction().begin();
        q.executeUpdate();

        em.getTransaction().commit();
        em.close();
        emf.close();

    }//GEN-LAST:event_btnDegistirDActionPerformed

    private void btnPersonelDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonelDegistirActionPerformed
        // TODO add your handling code here:
        PersonelGiris aboneGiris = new PersonelGiris();
        aboneGiris.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPersonelDegistirActionPerformed

    private void btnFaturalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaturalarActionPerformed
        // TODO add your handling code here:
        PanelFaturaTakip.setVisible(false);
        PanelFaturaListele.setVisible(true);

    }//GEN-LAST:event_btnFaturalarActionPerformed

    private void btnGeriFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriFaturaActionPerformed
        // TODO add your handling code here:
        PanelFaturaListele.setVisible(false);
        PanelFaturaTakip.setVisible(true);
        dlm.clear();
    }//GEN-LAST:event_btnGeriFaturaActionPerformed

    private void btnListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeleActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select f from Fatura f");
        List<Fatura> faturalar = q.getResultList();

        for (Fatura f : faturalar) {
            dlm.addElement(f.getAbone() + " Abonesinin " + f.getFaturaturu() + " faturası bulunmaktadır.");

        }

        em.close();
        emf.close();

    }//GEN-LAST:event_btnListeleActionPerformed

    private void btnAdreslerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdreslerActionPerformed
        // TODO add your handling code here:
        PanelFaturaTakip.setVisible(false);
        PanelFaturaAdresleri.setVisible(true);
    }//GEN-LAST:event_btnAdreslerActionPerformed

    private void btnGeriAdresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriAdresActionPerformed
        // TODO add your handling code here:
        PanelFaturaTakip.setVisible(true);
        PanelFaturaAdresleri.setVisible(false);
        cmbAdresler.removeAllItems();
    }//GEN-LAST:event_btnGeriAdresActionPerformed

    private void btnListeleAdresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeleAdresActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select f from Fatura f");
        List<Fatura> faturalar = q.getResultList();

        for (Fatura f : faturalar) {
            cmbAdresler.addItem(f.getAdres());

        }

        em.close();
        emf.close();

    }//GEN-LAST:event_btnListeleAdresActionPerformed

    private void btnFaturaÖdemeleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaturaÖdemeleriActionPerformed
        // TODO add your handling code here:
        PanelFaturaTakip.setVisible(false);
        PanelFaturaOdemeleri.setVisible(true);
    }//GEN-LAST:event_btnFaturaÖdemeleriActionPerformed

    private void btnGeriOdemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriOdemeActionPerformed
        // TODO add your handling code here:
        PanelFaturaTakip.setVisible(true);
        PanelFaturaOdemeleri.setVisible(false);
        dlmList.clear();
        txtToplamOdeme.setText("");
    }//GEN-LAST:event_btnGeriOdemeActionPerformed

    private void btnListeleOdemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeleOdemeActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select f from Fatura f");
        List<Fatura> faturalar = q.getResultList();

        for (Fatura f : faturalar) {
            dlmList.addElement(f.getAbone() + " abonesinin " + f.getFaturaturu() + " faturası " + f.getFaturatutari() + " TL'dir. ");

        }

        em.close();
        emf.close();

    }//GEN-LAST:event_btnListeleOdemeActionPerformed

    private void btnToplamOdemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToplamOdemeActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select f from Fatura f");
        List<Fatura> faturalar = q.getResultList();
        int toplamTutar = 0;

        for (Fatura f : faturalar) {
            toplamTutar += f.getFaturatutari();

        }

        txtToplamOdeme.setText(" Sistemde var olan aboneler toplamda " + String.valueOf(toplamTutar) + " TL ödeme yapmıştır.");

        em.close();
        emf.close();
    }//GEN-LAST:event_btnToplamOdemeActionPerformed

    private void btnAboneDurumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboneDurumActionPerformed
        // TODO add your handling code here:
        PanelFaturaTakip.setVisible(false);
        PanelAboneDurum.setVisible(true);
    }//GEN-LAST:event_btnAboneDurumActionPerformed

    private void btnGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGosterActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select f from Fatura f");
        List<Fatura> faturalar = q.getResultList();
        int toplamAbone = 0;

        toplamAbone = dtm.getRowCount();

        txtToplamAbone.setText(" Sistemde " + String.valueOf(toplamAbone) + " adet abone yer almaktadır.");

        em.close();
        emf.close();
    }//GEN-LAST:event_btnGosterActionPerformed

    private void btnGeriAboneDurumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriAboneDurumActionPerformed
        // TODO add your handling code here:
        PanelFaturaTakip.setVisible(true);
        PanelAboneDurum.setVisible(false);
    }//GEN-LAST:event_btnGeriAboneDurumActionPerformed

    private void btnHesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHesaplaActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select f from Fatura f");
        List<Fatura> faturalar = q.getResultList();
        int toplamAbone = 0;
        double ortalamaUcret = 0;
        int toplamTutar = 0;

        toplamAbone = dtm.getRowCount();
        for (Fatura f : faturalar) {
            toplamTutar += f.getFaturatutari();
            ortalamaUcret = (double) toplamTutar / (double) toplamAbone;

        }
        txtOrtalamaOdeme.setText("Ödenen ortalama fatura ücreti = " + String.valueOf(ortalamaUcret) + " TL'dir.");

        em.close();
        emf.close();
    }//GEN-LAST:event_btnHesaplaActionPerformed

    private void btnTarihGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarihGosterActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select f from Fatura f");
        List<Fatura> faturalar = q.getResultList();

        for (Fatura f : faturalar) {
            dlmAbone.addElement(f.getAbone() + " Abonesi " + f.getFaturaturu() + " faturasını " + f.getSonodemetarihi() + " tarihinden önce ödemelidir.");

        }

        em.close();
        emf.close();
    }//GEN-LAST:event_btnTarihGosterActionPerformed

    private void btnSorguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorguActionPerformed
        // TODO add your handling code here:
        PanelFaturaTakip.setVisible(false);
        PanelSorgu.setVisible(true);


    }//GEN-LAST:event_btnSorguActionPerformed

    private void btnGeriSorguSonucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriSorguSonucActionPerformed
        // TODO add your handling code here:
        PanelFaturaTakip.setVisible(true);
        PanelSorgu.setVisible(false);
    }//GEN-LAST:event_btnGeriSorguSonucActionPerformed

    private void btnSorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorgulaActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select f from Fatura f where f.faturano=:FATURANO");

        q.setParameter("FATURANO", Integer.parseInt(txtFaturaNoSorgu.getText()));
        List<Fatura> faturalar = q.getResultList();

        for (Fatura f : faturalar) {

            txtaSorguSonuc.setText("Abone İsmi : " + f.getAbone() + "\n"
                    + "Fatura Türü : " + f.getFaturaturu() + " Faturası " + "\n"
                    + "Fatura Tutarı : " + f.getFaturatutari() + "\n"
                    + "Faturanın İlk Ödeme Tarihi : " + f.getIlkodemetarihi() + "\n"
                    + "Faturanın Son Ödeme Tarihi : " + f.getSonodemetarihi() + "\n"
                    + "Faturanın Adresi : " + f.getAdres() + "\n");

            /*if(txtFaturaNoSorgu.getText().contains(f.getFaturano().toString())){
               txtaSorguSonuc.setText(f.getAbone());
           }else{
               txtaSorguSonuc.setText("bi bok yok");
           }*/
        }

        em.close();
        emf.close();

    }//GEN-LAST:event_btnSorgulaActionPerformed

    private void btnFaturaDosyaYazdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaturaDosyaYazdirActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select f from Fatura f");
        //q.setParameter("faturaturu", f.);
        List<Fatura> faturalar = q.getResultList();
        String dosya = "c:\\dosyalar\\fatura.txt";

        try {
            BufferedWriter f = new BufferedWriter(new FileWriter(dosya));
            for (Fatura fatura : faturalar) {
                f.write(fatura.getAbone() + " abonesinin " + fatura.getFaturano() + " numaralı " + fatura.getFaturaturu() + " faturası "
                        + fatura.getFaturatutari() + " TL'dir " + "\n");
            }
            f.close();
            em.close();
            emf.close();

        } catch (IOException ex) {
            Logger.getLogger(FaturaTakip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFaturaDosyaYazdirActionPerformed

    private void btnAboneDosyaYazdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboneDosyaYazdirActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select p from Personel p");
        //q.setParameter("faturaturu", f.);
        List<Personel> personeller = q.getResultList();
        String dosya = "c:\\dosyalar\\personel.txt";

        try {
            BufferedWriter f = new BufferedWriter(new FileWriter(dosya));
            for (Personel personel : personeller) {
                f.write(personel.getAdi() + " " + personel.getSoyadi() + " personeli " + personel.getŞube() + " şubesinde çalışmaktadır." + "\n");
            }

            f.close();
            em.close();
            emf.close();

        } catch (IOException ex) {
            Logger.getLogger(FaturaTakip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAboneDosyaYazdirActionPerformed

    private void btnDosyaOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosyaOkuActionPerformed
        // TODO add your handling code here:
        PanelFaturaTakip.setVisible(false);
        PanelDosyaOku.setVisible(true);
    }//GEN-LAST:event_btnDosyaOkuActionPerformed

    private void btnFaturaOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaturaOkuActionPerformed
        // TODO add your handling code here:
        dtm2.setColumnIdentifiers(new String[]{"Fatura Bilgileri"});

        String dosya = "c:\\dosyalar\\fatura.txt";
        BufferedReader reader = null;
        try {

            reader = new BufferedReader(new FileReader(dosya));
            String satir = reader.readLine();

            while (satir != null) {
                dtm2.addRow(new Object[]{satir});
                satir = reader.readLine();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FaturaTakip.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FaturaTakip.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                reader.close();
            } catch (IOException ex) {
                Logger.getLogger(FaturaTakip.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btnFaturaOkuActionPerformed

    private void btnPersonelOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonelOkuActionPerformed
        // TODO add your handling code here:
        dtm2.setColumnIdentifiers(new String[]{"Personel Bilgileri"});

        String dosya = "c:\\dosyalar\\personel.txt";
        BufferedReader reader = null;
        try {

            reader = new BufferedReader(new FileReader(dosya));
            String satir = reader.readLine();

            while (satir != null) {
                dtm2.addRow(new Object[]{satir});
                satir = reader.readLine();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FaturaTakip.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FaturaTakip.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                reader.close();
            } catch (IOException ex) {
                Logger.getLogger(FaturaTakip.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnPersonelOkuActionPerformed

    private void btnGeriOkumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriOkumaActionPerformed
        // TODO add your handling code here:
        PanelDosyaOku.setVisible(false);
        PanelFaturaTakip.setVisible(true);

    }//GEN-LAST:event_btnGeriOkumaActionPerformed

    private void btnYenileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYenileActionPerformed
        // TODO add your handling code here:
        dtm.setColumnIdentifiers(new String[]{"FATURANO", "FATURATURU", "ILKODEMETARIHI", "SONODEMETARIHI", "FATURATUTARI", "ADRES", "ABONE"});
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select f from Fatura f ");
        List<Fatura> faturalar = q.getResultList();
        dtm.setRowCount(0);
        for (Fatura f : faturalar) {
            dtm.addRow(new Object[]{f.getFaturano(), f.getFaturaturu(), f.getIlkodemetarihi(), f.getSonodemetarihi(), f.getFaturatutari(), f.getAdres(), f.getAbone()});
        }
        tblGoster.setModel(dtm);
        
    }//GEN-LAST:event_btnYenileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaturaTakip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaturaTakip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaturaTakip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaturaTakip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaturaTakip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAboneDurum;
    private javax.swing.JPanel PanelDegistir;
    private javax.swing.JPanel PanelDosyaOku;
    private javax.swing.JPanel PanelFaturaAdresleri;
    private javax.swing.JPanel PanelFaturaListele;
    private javax.swing.JPanel PanelFaturaOdemeleri;
    private javax.swing.JPanel PanelFaturaTakip;
    private javax.swing.JPanel PanelSil;
    private javax.swing.JPanel PanelSorgu;
    private javax.swing.JButton btnAboneDosyaYazdir;
    private javax.swing.JButton btnAboneDurum;
    private javax.swing.JButton btnAdresler;
    private javax.swing.JButton btnDegistir;
    private javax.swing.JButton btnDegistirD;
    private javax.swing.JButton btnDosyaOku;
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnFaturaDosyaYazdir;
    private javax.swing.JButton btnFaturaOku;
    private javax.swing.JButton btnFaturalar;
    private javax.swing.JButton btnFaturaÖdemeleri;
    private javax.swing.JButton btnGeri;
    private javax.swing.JButton btnGeriAboneDurum;
    private javax.swing.JButton btnGeriAdres;
    private javax.swing.JButton btnGeriDegistir;
    private javax.swing.JButton btnGeriFatura;
    private javax.swing.JButton btnGeriOdeme;
    private javax.swing.JButton btnGeriOkuma;
    private javax.swing.JButton btnGeriSorguSonuc;
    private javax.swing.JButton btnGoster;
    private javax.swing.JButton btnHesapla;
    private javax.swing.JButton btnListele;
    private javax.swing.JButton btnListeleAdres;
    private javax.swing.JButton btnListeleOdeme;
    private javax.swing.JButton btnPersonelDegistir;
    private javax.swing.JButton btnPersonelOku;
    private javax.swing.JButton btnSil;
    private javax.swing.JButton btnSorgu;
    private javax.swing.JButton btnSorgula;
    private javax.swing.JButton btnSİl;
    private javax.swing.JButton btnTarihGoster;
    private javax.swing.JButton btnToplamOdeme;
    private javax.swing.JButton btnYenile;
    private javax.swing.JComboBox<String> cmbAdresler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblAboneDurumGoster;
    private javax.swing.JLabel lblBilgi;
    private javax.swing.JLabel lblBilgiSorgulama;
    private javax.swing.JLabel lblDegistirmek;
    private javax.swing.JLabel lblFaturaAdresBilgi;
    private javax.swing.JLabel lblFaturaNo;
    private javax.swing.JLabel lblFaturaNoSorgu;
    private javax.swing.JLabel lblFaturaOdemeBilgi;
    private javax.swing.JLabel lblSonOdeme;
    private javax.swing.JLabel lblToplamAboneSayisi;
    private javax.swing.JLabel lblfaturaNoDegistir;
    private javax.swing.JList<String> listAboneDurum;
    private javax.swing.JList<String> listFatura;
    private javax.swing.JList<String> listFaturaOdeme;
    private javax.swing.JTable tblDosyaOku;
    private javax.swing.JTable tblGoster;
    private javax.swing.JTextField txtFaturaNo;
    private javax.swing.JTextField txtFaturaNoDegistir;
    private javax.swing.JTextField txtFaturaNoSorgu;
    private javax.swing.JTextField txtOrtalamaOdeme;
    private javax.swing.JTextField txtToplamAbone;
    private javax.swing.JTextField txtToplamOdeme;
    private javax.swing.JTextField txtYeniFatura;
    private javax.swing.JTextArea txtaSorguSonuc;
    // End of variables declaration//GEN-END:variables

}
