/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package faturatakip;

import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author Emre USTA
 */
public class FaturaEkleme extends javax.swing.JFrame {

    /**
     * Creates new form FaturaEkleme
     */
    public FaturaEkleme() {
        initComponents();
        setTitle("Fatura Ekleme Ekranı");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSec = new javax.swing.JPanel();
        lblBilgiVer = new javax.swing.JLabel();
        lblFaturaNo = new javax.swing.JLabel();
        lblFaturaTuru = new javax.swing.JLabel();
        lblIlkOdeme = new javax.swing.JLabel();
        lblSonOdeme = new javax.swing.JLabel();
        lblFaturaTutari = new javax.swing.JLabel();
        lblAdres = new javax.swing.JLabel();
        lblAbone = new javax.swing.JLabel();
        txtFaturaNo = new javax.swing.JTextField();
        txtFaturaTuru = new javax.swing.JTextField();
        txtIlkOdeme = new javax.swing.JTextField();
        txtSonOdeme = new javax.swing.JTextField();
        txtFaturaTutari = new javax.swing.JTextField();
        txtAdres = new javax.swing.JTextField();
        txtAbone = new javax.swing.JTextField();
        btnKaydet = new javax.swing.JButton();
        btnGeri = new javax.swing.JButton();
        lblFaturaNoDurum = new javax.swing.JLabel();
        lblFaturaTuruDurum = new javax.swing.JLabel();
        lblIlkOdemeDurum = new javax.swing.JLabel();
        lblSonOdemeDurum = new javax.swing.JLabel();
        lblFaturaTutariDurum = new javax.swing.JLabel();
        lblAdresDurum = new javax.swing.JLabel();
        lblAboneDurum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBilgiVer.setText("Lütfen Bilgileri Giriniz.");

        lblFaturaNo.setText("Fatura Numarası :");

        lblFaturaTuru.setText("Fatura Türü :");

        lblIlkOdeme.setText("İlk Ödeme Tarihi :");

        lblSonOdeme.setText("Son Ödeme Tarihi :");

        lblFaturaTutari.setText("Fatura Tutarı");

        lblAdres.setText("Adres :");

        lblAbone.setText("Abone :");

        btnKaydet.setText("Kaydet");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        btnGeri.setText("Geri");
        btnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSecLayout = new javax.swing.GroupLayout(PanelSec);
        PanelSec.setLayout(PanelSecLayout);
        PanelSecLayout.setHorizontalGroup(
            PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSecLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSecLayout.createSequentialGroup()
                        .addComponent(lblSonOdeme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelSecLayout.createSequentialGroup()
                        .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFaturaTuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFaturaNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelSecLayout.createSequentialGroup()
                                .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIlkOdeme, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFaturaTutari)
                                    .addComponent(lblAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAbone, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtAdres, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtFaturaNo)
                    .addComponent(txtFaturaTuru)
                    .addComponent(txtIlkOdeme)
                    .addComponent(txtSonOdeme)
                    .addComponent(txtFaturaTutari)
                    .addComponent(txtAbone))
                .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSecLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelSecLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(lblFaturaNoDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblFaturaTuruDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIlkOdemeDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSonOdemeDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFaturaTutariDurum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelSecLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdresDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAboneDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(PanelSecLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(lblBilgiVer)
                .addGap(64, 64, 64)
                .addComponent(btnKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGeri, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        PanelSecLayout.setVerticalGroup(
            PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSecLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBilgiVer)
                    .addComponent(btnGeri)
                    .addComponent(btnKaydet))
                .addGap(14, 14, 14)
                .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaturaNo)
                    .addComponent(txtFaturaNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFaturaNoDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFaturaTuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFaturaTuru)
                    .addComponent(lblFaturaTuruDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIlkOdeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIlkOdeme)
                    .addComponent(lblIlkOdemeDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSonOdeme)
                    .addComponent(txtSonOdeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSonOdemeDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaturaTutari)
                    .addComponent(txtFaturaTutari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFaturaTutariDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdres)
                    .addComponent(txtAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdresDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAbone)
                    .addComponent(txtAbone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAboneDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriActionPerformed
        // TODO add your handling code here:
        FaturaTakip ft = new FaturaTakip();
        ft.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGeriActionPerformed

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        // TODO add your handling code here:
        Pattern numaraDesen = Pattern.compile("[0-9]");
        Matcher numaraYakala = numaraDesen.matcher(txtFaturaNo.getText());
        if (!numaraYakala.find()) {

            lblFaturaNoDurum.setText("Geçerli Bir Fatura Numarası Giriniz.");

        } else {
            lblFaturaNoDurum.setText("");
        }
        Pattern turDesen = Pattern.compile("^[a-zA-Z]+$");
        Matcher turYakala = turDesen.matcher(txtFaturaTuru.getText());
        if (!turYakala.find()) {

            lblFaturaTuruDurum.setText("Geçerli Bir Fatura Turu Giriniz.");

        } else {
            lblFaturaTuruDurum.setText("");
        }
        Pattern ılkOdemeDesen = Pattern.compile("[0-9]");
        Matcher ılkOdemeYakala = ılkOdemeDesen.matcher(txtIlkOdeme.getText());
        if (!ılkOdemeYakala.find()) {

            lblIlkOdemeDurum.setText("Geçerli Bir İlk Ödeme Tarihi Giriniz.");

        } else {
            lblIlkOdemeDurum.setText("");
        }
        Pattern sonOdemeDesen = Pattern.compile("[0-9]");
        Matcher sonOdemeYakala = sonOdemeDesen.matcher(txtSonOdeme.getText());
        if (!sonOdemeYakala.find()) {

            lblSonOdemeDurum.setText("Geçerli Bir Son Ödeme Tarihi Giriniz.");

        } else {
            lblSonOdemeDurum.setText("");
        }Pattern faturaTutariDesen = Pattern.compile("[0-9]");
        Matcher faturaTutariYakala = faturaTutariDesen.matcher(txtFaturaTutari.getText());
        if (!faturaTutariYakala.find()) {

            lblFaturaTutariDurum.setText("Geçerli Bir Fatura Tutarı Giriniz.");

        } else {
            lblFaturaTutariDurum.setText("");
        }
        Pattern adresDesen = Pattern.compile("^[a-zA-Z]+$");
        Matcher adresYakala = adresDesen.matcher(txtAdres.getText());
        if (!adresYakala.find()) {

            lblAdresDurum.setText("Geçerli Bir Adres Giriniz.");

        } else {
            lblAdresDurum.setText("");
        }
        Pattern aboneDesen = Pattern.compile("^[a-zA-Z]+$");
        Matcher aboneYakala = aboneDesen.matcher(txtAbone.getText());
        if (!aboneYakala.find()) {

            lblAboneDurum.setText("Geçerli Bir Abone  Giriniz.");

        } else {
            lblAboneDurum.setText("");
        }
        

        
        
        
        
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select f from Fatura f ");
        
        
       
        em.getTransaction().begin();
       
        Fatura f = new Fatura();
        f.setFaturano(Integer.valueOf(txtFaturaNo.getText()));
        f.setFaturaturu(txtFaturaTuru.getText());
        f.setIlkodemetarihi(Integer.valueOf(txtIlkOdeme.getText()));
        f.setSonodemetarihi(Integer.valueOf(txtSonOdeme.getText()));
        f.setFaturatutari(Integer.valueOf(txtFaturaTutari.getText()));
        f.setAdres(txtAdres.getText());
        f.setAbone(txtAbone.getText());
        em.persist(f);

        txtFaturaNo.setText("");
        txtFaturaTuru.setText("");
        txtIlkOdeme.setText("");
        txtSonOdeme.setText("");
        txtFaturaTutari.setText("");
        txtAdres.setText("");
        txtAbone.setText("");

        em.getTransaction().commit();
        em.close();
        emf.close();
    }//GEN-LAST:event_btnKaydetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaturaEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaturaEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaturaEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaturaEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaturaEkleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelSec;
    private javax.swing.JButton btnGeri;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JLabel lblAbone;
    private javax.swing.JLabel lblAboneDurum;
    private javax.swing.JLabel lblAdres;
    private javax.swing.JLabel lblAdresDurum;
    private javax.swing.JLabel lblBilgiVer;
    private javax.swing.JLabel lblFaturaNo;
    private javax.swing.JLabel lblFaturaNoDurum;
    private javax.swing.JLabel lblFaturaTuru;
    private javax.swing.JLabel lblFaturaTuruDurum;
    private javax.swing.JLabel lblFaturaTutari;
    private javax.swing.JLabel lblFaturaTutariDurum;
    private javax.swing.JLabel lblIlkOdeme;
    private javax.swing.JLabel lblIlkOdemeDurum;
    private javax.swing.JLabel lblSonOdeme;
    private javax.swing.JLabel lblSonOdemeDurum;
    private javax.swing.JTextField txtAbone;
    private javax.swing.JTextField txtAdres;
    private javax.swing.JTextField txtFaturaNo;
    private javax.swing.JTextField txtFaturaTuru;
    private javax.swing.JTextField txtFaturaTutari;
    private javax.swing.JTextField txtIlkOdeme;
    private javax.swing.JTextField txtSonOdeme;
    // End of variables declaration//GEN-END:variables
}
