/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package faturatakip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Emre USTA
 */
public class PersonelGiris extends javax.swing.JFrame {

    /**
     * Creates new form AboneGiris
     */
    DefaultListModel dlm = new DefaultListModel();
    public PersonelGiris() {
        initComponents();
        setTitle("Personel Giriş Ekranı");
        listSubeler.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGiris = new javax.swing.JPanel();
        lblPersonelNo = new javax.swing.JLabel();
        lblTc = new javax.swing.JLabel();
        txtTc = new javax.swing.JTextField();
        txtPersonelNo = new javax.swing.JTextField();
        lblResim = new javax.swing.JLabel();
        btnGiris = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPersonelDurum = new javax.swing.JLabel();
        lblTcDurum = new javax.swing.JLabel();
        btnPersonelEkle = new javax.swing.JButton();
        btnSubelerimiz = new javax.swing.JButton();
        PanelPersonelKayit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTcPersonel = new javax.swing.JLabel();
        lblAdiPersonel = new javax.swing.JLabel();
        lblSoyadıPersonel = new javax.swing.JLabel();
        lblPersonelNoPersonel = new javax.swing.JLabel();
        lblŞube = new javax.swing.JLabel();
        txtTcPersonel = new javax.swing.JTextField();
        txtAdiPersonel = new javax.swing.JTextField();
        txtSoyadiPersonel = new javax.swing.JTextField();
        txtPersonelNoPersonel = new javax.swing.JTextField();
        txtSubePersonel = new javax.swing.JTextField();
        btnGonderPersonel = new javax.swing.JButton();
        btnTemizlePersonel = new javax.swing.JButton();
        btnSilPersonel = new javax.swing.JButton();
        btnGeriPersonel = new javax.swing.JButton();
        lblTCDurumPersonel = new javax.swing.JLabel();
        lblŞubeDurumPersonel = new javax.swing.JLabel();
        lblPersonelNoDurumP = new javax.swing.JLabel();
        lblSoyadiDurumPersonel = new javax.swing.JLabel();
        lblAdıDurumPersonel = new javax.swing.JLabel();
        PanelSube = new javax.swing.JPanel();
        lblSubeNo = new javax.swing.JLabel();
        lblSubeAdi = new javax.swing.JLabel();
        lblSubeIlce = new javax.swing.JLabel();
        lblSubeİl = new javax.swing.JLabel();
        txtSubeNumarasi = new javax.swing.JTextField();
        txtSubeAdi = new javax.swing.JTextField();
        txtSubeIlce = new javax.swing.JTextField();
        txtSubeIli = new javax.swing.JTextField();
        lblSubeGoster = new javax.swing.JLabel();
        btnSubeEkle = new javax.swing.JButton();
        btnGeriSube = new javax.swing.JButton();
        lblSubeNoDurum = new javax.swing.JLabel();
        lblSubeIlceDurum = new javax.swing.JLabel();
        lblSubeAdiDurum = new javax.swing.JLabel();
        lblSubeIliDurum = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSubeler = new javax.swing.JList<>();
        btnGoruntule = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        PanelGiris.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblPersonelNo.setText("Personel Numarası :");

        lblTc.setText("TC Kimlik No : ");

        lblResim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faturatakip/Başlıksız-1_1.jpg"))); // NOI18N

        btnGiris.setText("Giris");
        btnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faturatakip/login_icon_1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faturatakip/uye_ol.png"))); // NOI18N

        btnPersonelEkle.setText("Personel Ekle");
        btnPersonelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonelEkleActionPerformed(evt);
            }
        });

        btnSubelerimiz.setText("Şubelerimiz");
        btnSubelerimiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubelerimizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGirisLayout = new javax.swing.GroupLayout(PanelGiris);
        PanelGiris.setLayout(PanelGirisLayout);
        PanelGirisLayout.setHorizontalGroup(
            PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGirisLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGirisLayout.createSequentialGroup()
                        .addComponent(lblResim, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelGirisLayout.createSequentialGroup()
                        .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PanelGirisLayout.createSequentialGroup()
                                .addComponent(lblTc, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelGirisLayout.createSequentialGroup()
                                .addComponent(lblPersonelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPersonelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelGirisLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPersonelEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelGirisLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubelerimiz)
                            .addComponent(lblPersonelDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTcDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelGirisLayout.setVerticalGroup(
            PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGirisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResim, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGirisLayout.createSequentialGroup()
                        .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnGiris)
                                .addComponent(txtTc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTc, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPersonelEkle)
                                .addComponent(txtPersonelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPersonelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelGirisLayout.createSequentialGroup()
                        .addComponent(lblTcDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPersonelDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77)
                .addComponent(btnSubelerimiz)
                .addGap(64, 64, 64))
        );

        getContentPane().add(PanelGiris, "card10");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Yeni Personel Kayıt ");

        lblTcPersonel.setText("Tc Numarası : ");

        lblAdiPersonel.setText("Adı :");

        lblSoyadıPersonel.setText("Soyadı:");

        lblPersonelNoPersonel.setText("Personel Numarası:");

        lblŞube.setText("Şube :");

        btnGonderPersonel.setText("Gonder");
        btnGonderPersonel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGonderPersonelActionPerformed(evt);
            }
        });

        btnTemizlePersonel.setText("Temizle");
        btnTemizlePersonel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemizlePersonelActionPerformed(evt);
            }
        });

        btnSilPersonel.setText("Sil");
        btnSilPersonel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilPersonelActionPerformed(evt);
            }
        });

        btnGeriPersonel.setText("Geri");
        btnGeriPersonel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriPersonelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPersonelKayitLayout = new javax.swing.GroupLayout(PanelPersonelKayit);
        PanelPersonelKayit.setLayout(PanelPersonelKayitLayout);
        PanelPersonelKayitLayout.setHorizontalGroup(
            PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonelKayitLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTcPersonel)
                    .addComponent(lblAdiPersonel)
                    .addComponent(lblSoyadıPersonel)
                    .addComponent(lblPersonelNoPersonel)
                    .addComponent(lblŞube))
                .addGap(29, 29, 29)
                .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPersonelKayitLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelPersonelKayitLayout.createSequentialGroup()
                        .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTcPersonel, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(txtAdiPersonel)
                            .addComponent(txtSoyadiPersonel)
                            .addComponent(txtPersonelNoPersonel)
                            .addComponent(txtSubePersonel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelPersonelKayitLayout.createSequentialGroup()
                                .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblŞubeDurumPersonel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPersonelNoDurumP, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGeriPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelPersonelKayitLayout.createSequentialGroup()
                                .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTCDurumPersonel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAdıDurumPersonel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(lblSoyadiDurumPersonel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGonderPersonel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTemizlePersonel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSilPersonel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28))))
        );
        PanelPersonelKayitLayout.setVerticalGroup(
            PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonelKayitLayout.createSequentialGroup()
                .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPersonelKayitLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTcPersonel)
                            .addComponent(txtTcPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTCDurumPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAdiPersonel)
                                .addComponent(txtAdiPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAdıDurumPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPersonelKayitLayout.createSequentialGroup()
                                .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSoyadıPersonel)
                                    .addComponent(txtSoyadiPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPersonelNoPersonel)
                                    .addComponent(txtPersonelNoPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelPersonelKayitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblŞube)
                                    .addComponent(txtSubePersonel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelPersonelKayitLayout.createSequentialGroup()
                                .addComponent(lblSoyadiDurumPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(lblPersonelNoDurumP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblŞubeDurumPersonel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelPersonelKayitLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnGonderPersonel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTemizlePersonel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSilPersonel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGeriPersonel)))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        getContentPane().add(PanelPersonelKayit, "card4");

        lblSubeNo.setText("Şube Numarası :");

        lblSubeAdi.setText("Şube Adı :");

        lblSubeIlce.setText("Şube İlçesi :");

        lblSubeİl.setText("Sube İli");

        lblSubeGoster.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSubeGoster.setText("Şube Ekleyebilirsiniz ");

        btnSubeEkle.setText("Şube Ekle");
        btnSubeEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubeEkleActionPerformed(evt);
            }
        });

        btnGeriSube.setText("Geri");
        btnGeriSube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriSubeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Şube Görüntüleme");

        jScrollPane1.setViewportView(listSubeler);

        btnGoruntule.setText("Görüntüle");
        btnGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoruntuleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSubeLayout = new javax.swing.GroupLayout(PanelSube);
        PanelSube.setLayout(PanelSubeLayout);
        PanelSubeLayout.setHorizontalGroup(
            PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSubeLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubeAdi)
                    .addComponent(lblSubeIlce)
                    .addComponent(lblSubeİl)
                    .addComponent(btnGoruntule)
                    .addComponent(lblSubeNo))
                .addGap(26, 26, 26)
                .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubeGoster)
                    .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblSubeAdiDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelSubeLayout.createSequentialGroup()
                            .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSubeNumarasi, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSubeAdi, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSubeIlce, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSubeIli, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelSubeLayout.createSequentialGroup()
                                    .addComponent(btnSubeEkle)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnGeriSube)))
                            .addGap(32, 32, 32)
                            .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblSubeNoDurum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(lblSubeIlceDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSubeIliDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelSubeLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PanelSubeLayout.setVerticalGroup(
            PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSubeLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblSubeGoster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSubeNumarasi)
                        .addComponent(lblSubeNo))
                    .addComponent(lblSubeNoDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSubeAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSubeAdi))
                    .addComponent(lblSubeAdiDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubeIlce)
                    .addGroup(PanelSubeLayout.createSequentialGroup()
                        .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSubeIlce)
                            .addComponent(lblSubeIlceDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubeIliDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSubeIli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSubeİl)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubeEkle)
                    .addComponent(btnGeriSube))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGroup(PanelSubeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSubeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSubeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGoruntule)
                        .addGap(80, 80, 80))))
        );

        getContentPane().add(PanelSube, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGonderPersonelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGonderPersonelActionPerformed
        // TODO add your handling code here:
        Pattern tcDesenP = Pattern.compile("[0-9]");
        Matcher tcYakalaP = tcDesenP.matcher(txtTcPersonel.getText());
        if (!tcYakalaP.find()) {

            lblTCDurumPersonel.setText("Geçerli Bir Tc Kimlik Numarası Giriniz.");

        } else {
            lblTCDurumPersonel.setText("");
        }
        Pattern adDesenP = Pattern.compile("^[a-zA-Z]+$");
        Matcher adYakalaP = adDesenP.matcher(txtAdiPersonel.getText());
        if (!adYakalaP.find()) {
            lblAdıDurumPersonel.setText("Geçerli Ad Giriniz.");
        } else {
            lblAdıDurumPersonel.setText("");
        }
        Pattern soyadDesenP = Pattern.compile("^[a-zA-Z]+$");
        Matcher soyadYakalaP = soyadDesenP.matcher(txtSoyadiPersonel.getText());
        if (!soyadYakalaP.find()) {
            lblSoyadiDurumPersonel.setText("Geçerli Soyad Giriniz.");
        } else {
            lblSoyadiDurumPersonel.setText("");
        }
        Pattern personelNoDesen = Pattern.compile("[0-9]");
        Matcher personelNoYakala = personelNoDesen.matcher(txtPersonelNoPersonel.getText());
        if (!personelNoYakala.find()) {

            lblPersonelNoDurumP.setText("Geçerli Bir Personel Numarası Giriniz.");

        } else {
            lblPersonelNoDurumP.setText("");
        }
        Pattern subeDesen = Pattern.compile("^[a-zA-Z]+$");
        Matcher subeYakala = subeDesen.matcher(txtSubePersonel.getText());
        if (!subeYakala.find()) {
            lblŞubeDurumPersonel.setText("Geçerli Şube Giriniz.");
        } else {
            lblŞubeDurumPersonel.setText("");
        }
        
        
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Odev ", "odev", "odev");
            String sqlSorgu = "SELECT * FROM personel WHERE TC=?";
            PreparedStatement psSorgu = con.prepareStatement(sqlSorgu);
            psSorgu.setInt(1, Integer.parseInt(txtTcPersonel.getText()));
            ResultSet rs = psSorgu.executeQuery();

            if (rs.next()) {
                String sqlUpdate = "UPDATE personel" + "SET ADI=?,SOYADI=?,PERSONELNO=?,ŞUBE=?" + "WHERE TC=?";
                PreparedStatement psUpdate = con.prepareStatement(sqlUpdate);
                psUpdate.setInt(1, Integer.parseInt(txtTcPersonel.getText()));
                psUpdate.setString(2, txtAdiPersonel.getText());
                psUpdate.setString(3, txtSoyadiPersonel.getText());
                psUpdate.setInt(4, Integer.parseInt(txtPersonelNoPersonel.getText()));
                
                psUpdate.setString(5, txtSubePersonel.getText());
                psUpdate.executeUpdate();
            } else {
                String sqlInsert = "INSERT INTO PERSONEL "
                        + " (TC,ADI,SOYADI,PERSONELNO,ŞUBE) "
                        + " VALUES (?,?,?,?,?)";
                PreparedStatement psInsert = con.prepareStatement(sqlInsert);

                psInsert.setInt(1, Integer.parseInt(txtTcPersonel.getText()));
                psInsert.setString(2, txtAdiPersonel.getText());
                psInsert.setString(3, txtSoyadiPersonel.getText());
                psInsert.setInt(4, Integer.parseInt(txtPersonelNoPersonel.getText()));
               
                psInsert.setString(5, txtSubePersonel.getText());
                psInsert.executeUpdate();

                txtTcPersonel.setText("");
                txtAdiPersonel.setText("");
                txtSoyadiPersonel.setText("");
                txtPersonelNoPersonel.setText("");
                txtSubePersonel.setText("");
                

            }
        } catch (SQLException ex) {
            Logger.getLogger(PersonelGiris.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGonderPersonelActionPerformed

    private void btnTemizlePersonelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemizlePersonelActionPerformed
        // TODO add your handling code here:
        txtTcPersonel.setText(""); 
        txtAdiPersonel.setText("");
        txtSoyadiPersonel.setText("");
        txtPersonelNoPersonel.setText("");
        txtSubePersonel.setText("");
        
       
    }//GEN-LAST:event_btnTemizlePersonelActionPerformed

    private void btnSilPersonelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilPersonelActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Odev ", "odev", "odev");
            String sqlDelete = "DELETE FROM PERSONEL WHERE TC=?";
            PreparedStatement psDelete = con.prepareStatement(sqlDelete);
            psDelete.setInt(1, Integer.parseInt(txtTcPersonel.getText()));
            psDelete.executeUpdate();

            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(PersonelGiris.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSilPersonelActionPerformed

    private void btnGeriPersonelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriPersonelActionPerformed
        // TODO add your handling code here:
        PanelPersonelKayit.setVisible(false);
        PanelGiris.setVisible(true);
    }//GEN-LAST:event_btnGeriPersonelActionPerformed

    private void btnGeriSubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriSubeActionPerformed
        // TODO add your handling code here:PanelGiris.setVisible(false
        PanelGiris.setVisible(true);
        PanelSube.setVisible(false);
    }//GEN-LAST:event_btnGeriSubeActionPerformed

    private void btnSubeEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubeEkleActionPerformed
        // TODO add your handling code here:
        Pattern subeNoDesen = Pattern.compile("[0-9]");
        Matcher subeNoYakala = subeNoDesen.matcher(txtSubeNumarasi.getText());
        if (!subeNoYakala.find()) {

            lblSubeNoDurum.setText("Geçerli Bir Şube Numarası Giriniz.");

        } else {
            lblSubeNoDurum.setText("");
        }
        Pattern subeAdDesen = Pattern.compile("^[a-zA-Z]+$");
        Matcher subeAdYakala = subeAdDesen.matcher(txtSubeAdi.getText());
        if (!subeAdYakala.find()) {
            lblSubeAdiDurum.setText("Geçerli Şube Adı Giriniz.");
        } else {
            lblSubeAdiDurum.setText("");
        }
        Pattern subeIlceDesen = Pattern.compile("^[a-zA-Z]+$");
        Matcher subeIlceYakala = subeIlceDesen.matcher(txtSubeIlce.getText());
        if (!subeIlceYakala.find()) {
            lblSubeIlceDurum.setText("Geçerli Şube İlçesi Giriniz.");
        } else {
            lblSubeIlceDurum.setText("");
        }
        Pattern subeIlDesen = Pattern.compile("^[a-zA-Z]+$");
        Matcher subeIlYakala = subeIlDesen.matcher(txtSubeIli.getText());
        if (!subeIlYakala.find()) {
            lblSubeIliDurum.setText("Geçerli Şube İli Giriniz.");
        } else {
            lblSubeIliDurum.setText("");
        }
        
        
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Odev ", "odev", "odev");
            String sqlSorgu = "SELECT * FROM ŞUBELER WHERE ŞUBENO=?";
            PreparedStatement psSorgu = con.prepareStatement(sqlSorgu);
            psSorgu.setInt(1, Integer.parseInt(txtSubeNumarasi.getText()));
            ResultSet rs = psSorgu.executeQuery();

            if (rs.next()) {
                String sqlUpdate = "UPDATE ŞUBE" + "SET ŞUBEADI=?,SUBEILCE=?,SUBEIL=?" + "WHERE ŞUBENO=?";
                PreparedStatement psUpdate = con.prepareStatement(sqlUpdate);
                psUpdate.setInt(1, Integer.parseInt(txtSubeNumarasi.getText()));
                psUpdate.setString(2, txtSubeAdi.getText());
                psUpdate.setString(3, txtSubeIlce.getText());
                psUpdate.setString(4, txtSubeIli.getText());
                psUpdate.executeUpdate();
            } else {
                String sqlInsert = "INSERT INTO ŞUBELER "
                        + " (ŞUBENO,ŞUBEADI,SUBEILCE,SUBEIL) "
                        + " VALUES (?,?,?,?)";
                PreparedStatement psInsert = con.prepareStatement(sqlInsert);

                psInsert.setInt(1, Integer.parseInt(txtSubeNumarasi.getText()));
                psInsert.setString(2, txtSubeAdi.getText());
                psInsert.setString(3, txtSubeIlce.getText());
                psInsert.setString(4, txtSubeIli.getText());
               
               
                psInsert.executeUpdate();

                txtSubeNumarasi.setText("");
                txtSubeAdi.setText("");
                txtSubeIlce.setText("");
                txtSubeIli.setText("");
               
                

            }
        } catch (SQLException ex) {
            Logger.getLogger(PersonelGiris.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnSubeEkleActionPerformed

    private void btnGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoruntuleActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("OdevPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select s from Şubeler s");
        List<Şubeler>subeler = q.getResultList();
        
        for (Şubeler s : subeler) {
            dlm.addElement("Şube Adı : "+s.getŞubeadi() + " Bulunduğu İlçe " +s.getSubeilce()+" Bulunduğu İl :" +s.getSubeil() );
        }
                
       
        
    }//GEN-LAST:event_btnGoruntuleActionPerformed

    private void btnSubelerimizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubelerimizActionPerformed
        // TODO add your handling code here:
        PanelGiris.setVisible(false);
        PanelSube.setVisible(true);
    }//GEN-LAST:event_btnSubelerimizActionPerformed

    private void btnPersonelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonelEkleActionPerformed
        // TODO add your handling code here:
        PanelGiris.setVisible(false);
        PanelPersonelKayit.setVisible(true);
        
        
    }//GEN-LAST:event_btnPersonelEkleActionPerformed

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed

        try {
            // TODO add your handling code here:
            Pattern tcDesen = Pattern.compile("[0-9]");
            Pattern personelNoDesen = Pattern.compile("[0-9]");
            Matcher tcYakala = tcDesen.matcher(txtTc.getText());
            Matcher personelYakala = personelNoDesen.matcher(txtPersonelNo.getText());
            if (!tcYakala.find()) {

                lblTcDurum.setText("Yanlış Bilgi Girilmiştir.");

            } else {
                lblTcDurum.setText("");
            }
            if (!personelYakala.find()) {

                lblPersonelDurum.setText("Yanlış Bilgi Girilmiştir.");

            } else {
                lblPersonelDurum.setText("");
            }

            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Odev ", "odev", "odev");
            String sqlSorgu = "SELECT * FROM PERSONEL WHERE TC=?";
            PreparedStatement psSorgu = con.prepareStatement(sqlSorgu);
            psSorgu.setInt(1, Integer.parseInt(txtTc.getText()));
            ResultSet rs = psSorgu.executeQuery();

            if (rs.next()) {

                String TC = String.valueOf(rs.getInt("TC"));
                String PERSONELNO = String.valueOf(rs.getInt("PERSONELNO"));
                if (TC.equals(txtTc.getText()) && PERSONELNO.equals(txtPersonelNo.getText())) {
                    FaturaTakip ft = new FaturaTakip();

                    ft.setVisible(true);
                    this.dispose();

                } else /*if(txtTc.getText()==" " && txtPersonelNo.getText()==" ")*/ {
                    JOptionPane.showMessageDialog(this, "Bilgiler Doğru Girilmemiştir..");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(PersonelGiris.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelGiris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGiris;
    private javax.swing.JPanel PanelPersonelKayit;
    private javax.swing.JPanel PanelSube;
    private javax.swing.JButton btnGeriPersonel;
    private javax.swing.JButton btnGeriSube;
    private javax.swing.JButton btnGiris;
    private javax.swing.JButton btnGonderPersonel;
    private javax.swing.JButton btnGoruntule;
    private javax.swing.JButton btnPersonelEkle;
    private javax.swing.JButton btnSilPersonel;
    private javax.swing.JButton btnSubeEkle;
    private javax.swing.JButton btnSubelerimiz;
    private javax.swing.JButton btnTemizlePersonel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdiPersonel;
    private javax.swing.JLabel lblAdıDurumPersonel;
    private javax.swing.JLabel lblPersonelDurum;
    private javax.swing.JLabel lblPersonelNo;
    private javax.swing.JLabel lblPersonelNoDurumP;
    private javax.swing.JLabel lblPersonelNoPersonel;
    private javax.swing.JLabel lblResim;
    private javax.swing.JLabel lblSoyadiDurumPersonel;
    private javax.swing.JLabel lblSoyadıPersonel;
    private javax.swing.JLabel lblSubeAdi;
    private javax.swing.JLabel lblSubeAdiDurum;
    private javax.swing.JLabel lblSubeGoster;
    private javax.swing.JLabel lblSubeIlce;
    private javax.swing.JLabel lblSubeIlceDurum;
    private javax.swing.JLabel lblSubeIliDurum;
    private javax.swing.JLabel lblSubeNo;
    private javax.swing.JLabel lblSubeNoDurum;
    private javax.swing.JLabel lblSubeİl;
    private javax.swing.JLabel lblTCDurumPersonel;
    private javax.swing.JLabel lblTc;
    private javax.swing.JLabel lblTcDurum;
    private javax.swing.JLabel lblTcPersonel;
    private javax.swing.JLabel lblŞube;
    private javax.swing.JLabel lblŞubeDurumPersonel;
    private javax.swing.JList<String> listSubeler;
    private javax.swing.JTextField txtAdiPersonel;
    private javax.swing.JTextField txtPersonelNo;
    private javax.swing.JTextField txtPersonelNoPersonel;
    private javax.swing.JTextField txtSoyadiPersonel;
    private javax.swing.JTextField txtSubeAdi;
    private javax.swing.JTextField txtSubeIlce;
    private javax.swing.JTextField txtSubeIli;
    private javax.swing.JTextField txtSubeNumarasi;
    private javax.swing.JTextField txtSubePersonel;
    private javax.swing.JTextField txtTc;
    private javax.swing.JTextField txtTcPersonel;
    // End of variables declaration//GEN-END:variables
}
